Repository halo-dev/plugin-feed, pull requests merged in 2023-02, with the labels that each got.

#4 Create OWNERS
  OWNERS
Labels: release-note-none, do-not-merge/invalid-owners-file

#3 feat: RSS feeds by author, category and all posts
  .github/workflows/workflow.yaml
  .gitignore
  build.gradle
  compose/README.md
  compose/application.yaml
  compose/docker-compose.yaml
  gradle.properties
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  settings.gradle
  src/main/java/run/halo/feed/BasicSetting.java
  src/main/java/run/halo/feed/FeedPlugin.java
  src/main/java/run/halo/feed/FeedPluginEndpoint.java
  src/main/java/run/halo/feed/FeedService.java
  src/main/java/run/halo/feed/FeedServiceImpl.java
  src/main/java/run/halo/feed/FeedSourceFinder.java
  src/main/java/run/halo/feed/FeedSourceFinderImpl.java
  src/main/java/run/halo/feed/RSS2.java
  src/main/java/run/halo/feed/ReactiveSettingFetcher.java
  src/main/resources/extensions/settings.yaml
  src/main/resources/plugin.yaml
  src/test/java/run/halo/feed/RSS2Test.java
Labels: kind/feature, release-note, approved, lgtm

#5 docs: refine readme and remove compose folder
  README.md
  compose/README.md
  compose/application.yaml
  compose/docker-compose.yaml
Labels: release-note-none, kind/documentation, approved, lgtm

#6 chore: release 1.1.0-beta.1
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, lgtm
