Repository halo-dev/plugin-feed, pull requests merged in 2023-09, with the labels that each got.

#14 chore: add app id annotation
  .github/workflows/workflow.yaml
  src/main/resources/plugin.yaml
Labels: release-note, approved, kind/improvement, lgtm

#15 chore: update logo
  src/main/resources/logo.svg
  src/main/resources/plugin.yaml
Labels: release-note, approved, kind/improvement, lgtm

#16 chore: change repo organization to halo-dev
  README.md
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, kind/cleanup, lgtm

#18 Fix incorrect link protocol problem
  build.gradle
  src/main/java/run/halo/feed/FeedServiceImpl.java
  src/main/resources/plugin.yaml
Labels: release-note, approved, lgtm
