Repository halo-dev/plugin-feed, pull requests merged in 2023-04, with the labels that each got.

#8 fix: remove invalid xml characters in post content
  src/main/java/run/halo/feed/FeedServiceImpl.java
  src/main/java/run/halo/feed/XmlCharUtils.java
Labels: release-note, approved, lgtm

#10 Simplify build script
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  src/main/java/run/halo/feed/ContentWrapper.java
  src/main/java/run/halo/feed/FeedSourceFinder.java
  src/main/java/run/halo/feed/FeedSourceFinderImpl.java
  src/main/java/run/halo/feed/PatchUtils.java
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, lgtm

#11 Adapt to external URL that might not be a URL
  .editorconfig
  src/main/java/run/halo/feed/FeedPluginEndpoint.java
  src/main/java/run/halo/feed/FeedService.java
  src/main/java/run/halo/feed/FeedServiceImpl.java
Labels: kind/bug, release-note, approved, lgtm

#12 Change version to 1.1.1
  gradle.properties
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, kind/cleanup, lgtm
